name: TestEnvironment

on:
  workflow_dispatch:

jobs:
  job:
    runs-on:
      - ubuntu-latest
    environment: 'Production'
    steps:
      - name: 'Check Membership'
        uses: tspascoal/get-user-teams-membership@v2
        with:
          username: hakob
          team: devops
          GITHUB_TOKEN: ${{ secrets.MEMBERS_PAT }}
