name: TestEnvironment

on:
  workflow_dispatch:

jobs:
  job:
    runs-on:
      - ubuntu-latest
    environment: 'Production'
    steps:
      - name: Hello World
        run: |
          echo Hello World
